name: Auto_Bing_Search

on:
  workflow_dispatch:  # 允许手动触发
  #schedule:
    #- cron: '0 0,12 * * *'  # 每天UTC时间0点和12点运行（对应北京时间8点和20点）

jobs:
  automate-bing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Microsoft Edge
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
        sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
        sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list'
        sudo apt update
        sudo apt install microsoft-edge-stable -y

    - name: Install EdgeDriver
      run: |
        sudo apt-get install jq -y
        LATEST_VERSION=$(curl -s https://edgeupdates.microsoft.com/api/products | jq -r '.[] | select(.Product == "msedge") | .Releases[0].Version')
        wget https://msedgedriver.azureedge.net/$LATEST_VERSION/edgedriver_linux64.zip
        unzip edgedriver_linux64.zip
        sudo mv msedgedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/msedgedriver

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium msedge-selenium-tools

    - name: Run Bing automation
      run: python auto_bing_search.py

    - name: Upload log (optional)
      if: always()
      uses: actions/upload-artifact@v4  # 版本升级到v4
      with:
        name: console-log
        path: ${{ github.workspace }}/autobing-log.txt
