name: AutoBing Search

on:
  workflow_dispatch:
  #schedule:
    #- cron: '0 0,12 * * *'

jobs:
  automate-bing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 120
        install-chromedriver: true

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        sudo apt-get install -y libnss3  # Chrome依赖库
        
    - name: Run Bing automation
      run: |
        echo "当前工作目录: $(pwd)"
        echo "文件列表:"
        ls -la
        python auto_bing_search.py

    - name: Upload log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: console-log
        path: autobing-log.txt
