name: Auto Bing Search

on:
  workflow_dispatch:
  #schedule:
    #- cron: '0 0,12 * * *'

jobs:
  automate-bing:
    runs-on: ubuntu-latest
    timeout-minutes: 3  # 添加超时限制
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
          
    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        sudo apt-get install -y libnss3  # Chrome依赖库

    - name: Validate Chrome
      run: |
        echo "Chrome版本: $(google-chrome --version)"
        echo "ChromeDriver版本: $(chromedriver --version)" 
        
    - name: Run Bing automation
      run: |
        python auto_bing_search.py

    - name: Upload log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: console-log
        path: autobing-log.txt
